apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: static-binding
spec:
  template:
    spec:
      containers:
        - image: ../src # points to the directory containing package.json
          env:
            - name: P_SECONDS  # corresponds to the parameter named seconds
              value: "5"
